openapi: 3.0.3

info:
  title: ImageAPI
  description: |-
    A simple self-hosted image API made using express

    Links:
    - [The ImageAPI repository](https://github.com/niek-o/imageAPI)
  contact:
    email: frankenstein795@gmail.com
  license:
    name: MIT
    url: https://github.com/niek-o/imageAPI/blob/main/LICENSE.md
  version: 1.1.1

externalDocs:
  description: Repository
  url: https://github.com/niek-o/imageAPI

servers:
  - url: http://localhost:3000

paths:
  /:
    post:
      summary: Upload a new image to folder
      operationId: addImage

      requestBody:
        description: Create a new image in a folder
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/image"

      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid URL or Folder

  /{folder}:
    get:
      summary: Get an image from a folder in a Base64 formatted string
      operationId: getImageFromFolder

      parameters:
        - name: folder
          in: path
          description: The folder you want the image to be from
          required: true
          explode: true
          schema:
            type: string

      responses:
        '200':
          description: Successful operation
        '404':
          description: Image does not exist

components:
  schemas:
    image:
      type: object
      properties:
        path:
          type: string
          example: "cat"
        url:
          type: string
          example: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Cat_November_2010-1a.jpg/1200px-Cat_November_2010-1a.jpg"
      required:
        - path
        - url
